services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    depends_on:
      - php
      - mysql
    environment:
      - NGINX_CLIENT_MAX_BODY_SIZE=100M

  php:
    build: .
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOST=mysql
      - DB_NAME=police_training
      - DB_USER=police_user
      - DB_PASS=police_pass
      - TZ=Asia/Bangkok
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    command: --skip-name-resolve --innodb-buffer-pool-size=256M --max_allowed_packet=100M --default-time-zone='+07:00'
    environment:
      MYSQL_ROOT_PASSWORD: police123
      MYSQL_DATABASE: police_training
      MYSQL_USER: police_user
      MYSQL_PASSWORD: police_pass
      TZ: Asia/Bangkok
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: police_user
      PMA_PASSWORD: police_pass
    depends_on:
      - mysql

volumes:
  mysql_data:
